### ISSUE TITLE
Text on the nodes

### ISSUE THREAD

**Issue by stevenrbrandt** [StevenSeiden/DistributedGarbageGUI#2]
cid state
[strong, weak, phantom, rcc]
(weight / max_weight) wait

Ex:
(2,1,0) healthy
[1,1,0,0]
(3/2) 0

Node node
node.state (see CollectorState: healthy, phantom, recover, build, infected, dead)
node.strong_count
node.weak_count
node.cd.phantom_count
node.cd.rcc
node.weight
node.max_weight
node.cd.wait

**Comment by ghost** [comment]
Added and pushed.
