### ISSUE TITLE
not an issue - found this  (your?) cheat sheet from '94

### ISSUE THREAD

**Issue by johndpope** [StevenSeiden/DistributedGarbageGUI#8]
<img width="1198" alt="screen shot 2018-11-03 at 8 05 09 am" src="https://user-images.githubusercontent.com/289994/47952013-3c282e00-df3f-11e8-9b1c-3ee04a6b1f1b.png">

this is an amazing piece of work. Presumably you made this (it's linked in pdf2htmlEX repo)
 - I acknowledge your efforts. 

https://github.com/coolwanglu/pdf2htmlEX

**Comment by ghost** [comment]
Hi @johndpope , that paper was actually by my dad.  Unfortunately he passed away in 2002, but it's good to hear that people are still appreciating his work!
